[package]
name = "ouroborocessor"
version = "0.1.0-beta.1"
description = "Accessible, local-first long-form writing application"
authors = ["Kim Chanyoung <qurioturio@gmail.com>"]
license-file = "../LICENSE"
edition = "2021"

[lib]
name = "ouroborocessor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
atomicwrites = "0.4"
zip = { version = "4", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

[dev-dependencies]
tempfile = "3"
