import type { Locale } from "./i18n";

const en = {
  recentProjects: "Recent projects",
  reconnect: "Find new location",
  openFolder: "Open another folder",
  reopenTab: "Reopen closed tab",
  noRecent: "No recent projects.",
  missingProject: "Couldn’t open this project. If you moved its folder, find the new location.",
  searchProjects: "Search project name or folder",
  noMatchingProjects: "No matching projects.",
  removeRecent: "Remove from recent projects",
  removedRecent: "Removed from the list. Project files are unchanged.",
  undoRemove: "Undo removal",
  recentHint: "Removing an entry only changes this list. It does not delete project files.",
  switchSaveFailed: "Couldn’t save the current project. Opening another project was stopped to protect your work.",
};

export const featureText: Record<Locale, typeof en> = {
  en,
  ko: {
    recentProjects: "최근 프로젝트",
    reconnect: "새 위치 찾기",
    openFolder: "다른 폴더 열기",
    reopenTab: "닫은 탭 다시 열기",
    noRecent: "최근에 연 프로젝트가 없어요.",
    missingProject: "프로젝트를 열지 못했어요. 폴더를 옮겼다면 새 위치를 찾아 주세요.",
    searchProjects: "프로젝트 이름 또는 폴더 검색",
    noMatchingProjects: "검색 결과가 없어요.",
    removeRecent: "최근 목록에서 제거",
    removedRecent: "목록에서 제거했어요. 프로젝트 파일은 그대로예요.",
    undoRemove: "제거 되돌리기",
    recentHint: "목록에서 제거해도 프로젝트 파일은 삭제되지 않아요.",
    switchSaveFailed: "현재 프로젝트를 저장하지 못해 다른 프로젝트 열기를 중단했어요. 작성한 내용은 현재 창에 유지돼요.",
  },
  es: {
    recentProjects: "Proyectos recientes",
    reconnect: "Buscar nueva ubicación",
    openFolder: "Abrir otra carpeta",
    reopenTab: "Reabrir pestaña cerrada",
    noRecent: "No hay proyectos recientes.",
    missingProject: "No se pudo abrir el proyecto. Si moviste su carpeta, busca la nueva ubicación.",
    searchProjects: "Buscar por nombre o carpeta",
    noMatchingProjects: "No hay proyectos que coincidan.",
    removeRecent: "Quitar de proyectos recientes",
    removedRecent: "Se quitó de la lista. Los archivos del proyecto no han cambiado.",
    undoRemove: "Deshacer eliminación de la lista",
    recentHint: "Quitar un proyecto de esta lista no elimina sus archivos.",
    switchSaveFailed: "No se pudo guardar el proyecto actual. Se detuvo la apertura de otro proyecto para proteger tu trabajo.",
  },
  ja: {
    recentProjects: "最近のプロジェクト",
    reconnect: "新しい場所を探す",
    openFolder: "別のフォルダを開く",
    reopenTab: "閉じたタブを開き直す",
    noRecent: "最近開いたプロジェクトはありません。",
    missingProject: "プロジェクトを開けませんでした。フォルダを移動した場合は、新しい場所を指定してください。",
    searchProjects: "プロジェクト名またはフォルダを検索",
    noMatchingProjects: "一致するプロジェクトはありません。",
    removeRecent: "最近の一覧から削除",
    removedRecent: "一覧から削除しました。プロジェクトファイルは変更されません。",
    undoRemove: "一覧からの削除を取り消す",
    recentHint: "一覧から削除してもプロジェクトファイルは削除されません。",
    switchSaveFailed: "現在のプロジェクトを保存できませんでした。作業内容を守るため、別のプロジェクトを開く操作を中止しました。",
  },
  zh: {
    recentProjects: "最近的项目",
    reconnect: "查找新位置",
    openFolder: "打开其他文件夹",
    reopenTab: "重新打开已关闭的标签页",
    noRecent: "没有最近打开的项目。",
    missingProject: "无法打开此项目。如果移动过文件夹，请找到新的位置。",
    searchProjects: "搜索项目名称或文件夹",
    noMatchingProjects: "没有匹配的项目。",
    removeRecent: "从最近项目中移除",
    removedRecent: "已从列表中移除。项目文件保持不变。",
    undoRemove: "撤销移除",
    recentHint: "从列表中移除不会删除项目文件。",
    switchSaveFailed: "无法保存当前项目。为保护你的工作，已停止打开其他项目。",
  },
};
