import type { Locale } from "./i18n";
const en = {
  title: "Research cards", character: "Character", place: "Place", setting: "Setting", create: "New card", name: "Name", description: "Description", aliases: "Aliases (one per line)", tags: "Tags (one per line)", save: "Save card", discard: "Discard draft", edit: "Edit", trash: "Trash", remove: "Move to trash", restore: "Restore card", search: "Search cards", empty: "No matching cards.", saved: "Card saved.", draft: "Draft kept on this device. Save to include it in the project.", error: "Could not load or save. Your draft is kept. Check file permissions, then retry.", conflict: "This card changed outside the app. Your draft is kept; copy any needed text before discarding it and reloading.", retry: "Reload cards", loading: "Loading…", close: "Close", kind: "Type", help: "Local project research. Deleted cards can be restored from Trash.",
};
export const resourceText: Record<Locale, typeof en> = {
  en,
  ko: { title: "레퍼런스 카드", character: "인물", place: "장소", setting: "설정", create: "새 레퍼런스", name: "이름", description: "설명", aliases: "별칭 (한 줄에 하나)", tags: "태그 (한 줄에 하나)", save: "레퍼런스 저장", discard: "초안 버리기", edit: "수정", trash: "휴지통", remove: "휴지통으로 이동", restore: "레퍼런스 복원", search: "레퍼런스 검색", empty: "일치하는 레퍼런스가 없어요.", saved: "레퍼런스를 저장했어요.", draft: "초안은 이 기기에만 있어요. 프로젝트에 넣으려면 저장하세요.", error: "레퍼런스를 읽거나 저장하지 못했어요. 초안은 그대로 있어요. 파일 접근 권한을 확인한 뒤 다시 시도하세요.", conflict: "다른 곳에서 레퍼런스가 바뀌었어요. 초안은 그대로 있어요. 필요한 내용을 복사한 뒤 초안을 버리고 다시 불러오세요.", retry: "레퍼런스 다시 불러오기", loading: "불러오는 중…", close: "닫기", kind: "유형", help: "레퍼런스는 프로젝트 안에 저장돼요. 삭제한 레퍼런스는 휴지통에서 복원할 수 있어요." },
  es: { title: "Fichas de referencia", character: "Personaje", place: "Lugar", setting: "Ambientación", create: "Nueva ficha", name: "Nombre", description: "Descripción", aliases: "Alias (uno por línea)", tags: "Etiquetas (una por línea)", save: "Guardar ficha", discard: "Descartar borrador", edit: "Editar", trash: "Papelera", remove: "Mover a la papelera", restore: "Restaurar ficha", search: "Buscar fichas", empty: "No hay fichas coincidentes.", saved: "Ficha guardada.", draft: "Borrador guardado en este dispositivo. Guarda la ficha para incluirla en el proyecto.", error: "No se pudo cargar o guardar. Se conserva el borrador. Comprueba los permisos y reintenta.", conflict: "La ficha cambió fuera de la aplicación. Se conserva el borrador; copia el texto necesario antes de descartarlo y volver a cargar.", retry: "Volver a cargar", loading: "Cargando…", close: "Cerrar", kind: "Tipo", help: "Referencias locales del proyecto. Las fichas eliminadas se pueden restaurar desde la papelera." },
  ja: { title: "資料カード", character: "人物", place: "場所", setting: "設定", create: "新しい資料", name: "名前", description: "説明", aliases: "別名（1行に1つ）", tags: "タグ（1行に1つ）", save: "資料を保存", discard: "下書きを破棄", edit: "編集", trash: "ゴミ箱", remove: "ゴミ箱へ移動", restore: "資料を復元", search: "資料を検索", empty: "一致する資料はありません。", saved: "資料を保存しました。", draft: "下書きはこの端末に保管されます。プロジェクトに含めるには保存してください。", error: "読み込みまたは保存に失敗しました。下書きは保持されます。アクセス権を確認して再試行してください。", conflict: "アプリ外で資料が変更されました。下書きは保持されます。必要な本文をコピーしてから下書きを破棄し、再読み込みしてください。", retry: "資料を再読み込み", loading: "読み込み中…", close: "閉じる", kind: "種類", help: "プロジェクトにローカル保存する資料です。削除した資料はゴミ箱から復元できます。" },
  zh: { title: "资料卡片", character: "人物", place: "地点", setting: "设定", create: "新建资料", name: "名称", description: "说明", aliases: "别名（每行一个）", tags: "标签（每行一个）", save: "保存资料", discard: "丢弃草稿", edit: "编辑", trash: "回收站", remove: "移至回收站", restore: "恢复资料", search: "搜索资料", empty: "没有匹配的资料。", saved: "资料已保存。", draft: "草稿保存在此设备上。保存资料后才会包含在项目中。", error: "无法加载或保存。草稿已保留。请检查文件权限后重试。", conflict: "资料已在应用外更改。草稿已保留；请复制所需文本后丢弃草稿并重新加载。", retry: "重新加载资料", loading: "正在加载…", close: "关闭", kind: "类型", help: "本地项目资料。已删除的资料可从回收站恢复。" },
};
