import type { Locale } from "./i18n";

const en = {
  importManuscript: "Import manuscript",
  chooseFiles: "Choose files",
  splitHeadings: "Start a new document at each heading",
  importHint: "Choose UTF-8 TXT or Markdown files. The original files stay as they are, and new documents are added in the order below.",
  importAction: "Import",
  previewHint: "Expand a document to preview it. Long documents are shown in parts; importing includes the full text.",
  previewPrevious: "Previous part",
  previewNext: "Next part",
  previewPage: "Part {page} of {pages}",
  splitScene: "Split at cursor",
  mergeNext: "Merge with next document",
  splitTitle: "Title of the new document",
  splitHint: "Text after the cursor moves to a new document. You can’t split inside an image or a research link.",
  mergeHint: "The two documents are joined with a blank line between them. The next document goes to the trash with its notes, so you can restore it later.",
  moveTrash: "Move to trash",
  manuscriptTrash: "Manuscript trash",
  restore: "Restore",
  emptyTrash: "The trash is empty.",
  restoreParent: "Restore the parent folder first.",
  operationHint: "You can restore it from the manuscript trash. A folder goes to the trash together with everything inside it.",
  invalidImport: "Only UTF-8 TXT or Markdown files can be imported, up to 50 MB and 500 documents at a time.",
  operationInvalid: "This can’t be done here.",
  operationConflict: "The manuscript changed in the meantime, so nothing was changed. Check it and try again.",
  compare: "Compare with current text",
  added: "Added",
  removed: "Removed",
  copySelection: "Copy selection",
  copied: "Copied.",
  noChanges: "This version is the same as the current text.",
  goals: "Writing goals",
  enableGoals: "Use goals",
  dailyGoal: "Daily goal",
  projectGoal: "Project goal",
  includeSpaces: "Count spaces",
  goalHint: "Goals are counted in characters. Today’s progress is the number of characters you added on this device today, and deleting text lowers it. Importing, restoring, splitting and merging don’t count. Line breaks and images aren’t counted, and research links count only their visible names.",
};

export const writingToolsText: Record<Locale, typeof en> = {
  en,
  ko: {
    importManuscript: "원고 가져오기",
    chooseFiles: "파일 선택",
    splitHeadings: "제목이 나올 때마다 새 원고로 나누기",
    importHint: "TXT나 Markdown 파일(UTF-8)을 고르세요. 원래 파일은 그대로 두고, 아래 순서대로 새 원고를 추가해요.",
    importAction: "가져오기",
    previewHint: "원고를 펼치면 미리 볼 수 있어요. 긴 원고는 나누어 보여 주지만, 가져올 때는 전체 본문이 포함돼요.",
    previewPrevious: "이전 부분",
    previewNext: "다음 부분",
    previewPage: "{page} / {pages} 부분",
    splitScene: "커서 위치에서 나누기",
    mergeNext: "다음 원고와 합치기",
    splitTitle: "새 원고 제목",
    splitHint: "커서 뒤의 내용이 새 원고로 옮겨져요. 이미지나 레퍼런스 링크 중간에서는 나눌 수 없어요.",
    mergeHint: "두 원고 사이에 빈 줄을 넣어 하나로 합쳐요. 다음 원고는 메모와 함께 휴지통으로 옮겨지니 나중에 복원할 수 있어요.",
    moveTrash: "휴지통으로 옮기기",
    manuscriptTrash: "원고 휴지통",
    restore: "복원",
    emptyTrash: "휴지통이 비어 있어요.",
    restoreParent: "상위 폴더를 먼저 복원하세요.",
    operationHint: "원고 휴지통에서 다시 복원할 수 있어요. 폴더를 옮기면 안에 있는 원고도 함께 옮겨져요.",
    invalidImport: "UTF-8로 저장된 TXT·Markdown 파일만 가져올 수 있어요. 한 번에 50MB, 원고 500개까지 가능해요.",
    operationInvalid: "여기서는 할 수 없는 작업이에요.",
    operationConflict: "그사이 원고가 바뀌어서 아무것도 바꾸지 않았어요. 내용을 확인한 뒤 다시 시도하세요.",
    compare: "지금 원고와 비교",
    added: "추가됨",
    removed: "삭제됨",
    copySelection: "선택한 부분 복사",
    copied: "복사했어요.",
    noChanges: "지금 원고와 내용이 같아요.",
    goals: "집필 목표",
    enableGoals: "목표 사용",
    dailyGoal: "하루 목표",
    projectGoal: "작품 목표",
    includeSpaces: "공백도 글자 수에 포함",
    goalHint: "목표는 글자 수로 계산해요. 오늘 진행량은 이 기기에서 오늘 늘어난 글자 수이고, 글을 지우면 그만큼 줄어요. 가져오기, 복원, 나누기, 합치기는 포함하지 않아요. 줄바꿈과 이미지는 세지 않고, 레퍼런스 링크는 화면에 보이는 이름만 글자 수에 들어가요.",
  },
  es: {
    importManuscript: "Importar manuscrito",
    chooseFiles: "Elegir archivos",
    splitHeadings: "Crear un documento nuevo en cada encabezado",
    importHint: "Elige archivos TXT o Markdown en UTF-8. Los archivos originales no cambian y los documentos nuevos se añaden en el orden de abajo.",
    importAction: "Importar",
    previewHint: "Abre un documento para verlo. Los documentos largos se muestran por partes; al importar se incluye todo el texto.",
    previewPrevious: "Parte anterior",
    previewNext: "Parte siguiente",
    previewPage: "Parte {page} de {pages}",
    splitScene: "Dividir en el cursor",
    mergeNext: "Unir con el siguiente documento",
    splitTitle: "Título del nuevo documento",
    splitHint: "El texto que sigue al cursor pasa a un documento nuevo. No se puede dividir dentro de una imagen ni de un enlace de referencia.",
    mergeHint: "Los dos documentos se unen con una línea en blanco entre ellos. El siguiente documento pasa a la papelera con sus notas, así que puedes restaurarlo más tarde.",
    moveTrash: "Mover a la papelera",
    manuscriptTrash: "Papelera del manuscrito",
    restore: "Restaurar",
    emptyTrash: "La papelera está vacía.",
    restoreParent: "Restaura primero la carpeta superior.",
    operationHint: "Puedes restaurarlo desde la papelera del manuscrito. Una carpeta pasa a la papelera junto con todo su contenido.",
    invalidImport: "Solo se pueden importar archivos TXT o Markdown en UTF-8, hasta 50 MB y 500 documentos a la vez.",
    operationInvalid: "Esta acción no se puede hacer aquí.",
    operationConflict: "El manuscrito cambió mientras tanto, así que no se ha modificado nada. Revísalo e inténtalo de nuevo.",
    compare: "Comparar con el texto actual",
    added: "Añadido",
    removed: "Eliminado",
    copySelection: "Copiar selección",
    copied: "Copiado.",
    noChanges: "Esta versión es igual al texto actual.",
    goals: "Objetivos de escritura",
    enableGoals: "Usar objetivos",
    dailyGoal: "Objetivo diario",
    projectGoal: "Objetivo del proyecto",
    includeSpaces: "Contar espacios",
    goalHint: "Los objetivos se cuentan en caracteres. El progreso de hoy son los caracteres que añadiste hoy en este dispositivo; al borrar texto, baja. Importar, restaurar, dividir y unir no cuentan. No se cuentan los saltos de línea ni las imágenes, y los enlaces de referencia cuentan solo su nombre visible.",
  },
  ja: {
    importManuscript: "原稿を読み込む",
    chooseFiles: "ファイルを選択",
    splitHeadings: "見出しごとに新しい原稿に分ける",
    importHint: "UTF-8のTXTまたはMarkdownファイルを選んでください。元のファイルはそのまま残り、新しい原稿が下の順番で追加されます。",
    importAction: "読み込む",
    previewHint: "原稿を開くとプレビューできます。長い原稿は分けて表示しますが、読み込みには本文全体が含まれます。",
    previewPrevious: "前の部分",
    previewNext: "次の部分",
    previewPage: "{page} / {pages} 部分",
    splitScene: "カーソル位置で分割",
    mergeNext: "次の原稿と結合",
    splitTitle: "新しい原稿のタイトル",
    splitHint: "カーソルより後の文章が新しい原稿に移ります。画像や資料リンクの途中では分割できません。",
    mergeHint: "2つの原稿を空行をはさんで1つにまとめます。次の原稿はメモと一緒にゴミ箱に移るので、後で復元できます。",
    moveTrash: "ゴミ箱に移動",
    manuscriptTrash: "原稿のゴミ箱",
    restore: "復元",
    emptyTrash: "ゴミ箱は空です。",
    restoreParent: "先に上位フォルダを復元してください。",
    operationHint: "原稿のゴミ箱から復元できます。フォルダを移動すると、中の原稿も一緒に移動します。",
    invalidImport: "読み込めるのはUTF-8のTXT・Markdownファイルだけです。一度に50 MB、原稿500件までです。",
    operationInvalid: "ここではこの操作を実行できません。",
    operationConflict: "その間に原稿が変更されたため、何も変更していません。内容を確認してからもう一度お試しください。",
    compare: "現在の原稿と比較",
    added: "追加",
    removed: "削除",
    copySelection: "選択した部分をコピー",
    copied: "コピーしました。",
    noChanges: "現在の原稿と同じ内容です。",
    goals: "執筆目標",
    enableGoals: "目標を使う",
    dailyGoal: "1日の目標",
    projectGoal: "作品の目標",
    includeSpaces: "空白も文字数に含める",
    goalHint: "目標は文字数で数えます。今日の進み具合は、この端末で今日増えた文字数で、文章を消すとその分減ります。読み込み・復元・分割・結合は含みません。改行と画像は数えず、資料リンクは表示されている名前だけを数えます。",
  },
  zh: {
    importManuscript: "导入稿件",
    chooseFiles: "选择文件",
    splitHeadings: "每遇到标题就拆成新文稿",
    importHint: "请选择 UTF-8 编码的 TXT 或 Markdown 文件。原文件保持不变，新文稿会按下方顺序添加。",
    importAction: "导入",
    previewHint: "展开文稿即可预览。长文稿会分段显示，导入时仍包含完整正文。",
    previewPrevious: "上一部分",
    previewNext: "下一部分",
    previewPage: "第 {page} / {pages} 部分",
    splitScene: "在光标处拆分",
    mergeNext: "与下一个文稿合并",
    splitTitle: "新文稿标题",
    splitHint: "光标之后的内容会移到新文稿中。不能在图片或资料链接中间拆分。",
    mergeHint: "两个文稿之间会插入一个空行后合并。下一个文稿会连同备注移到回收站，之后可以恢复。",
    moveTrash: "移到回收站",
    manuscriptTrash: "稿件回收站",
    restore: "恢复",
    emptyTrash: "回收站是空的。",
    restoreParent: "请先恢复上级文件夹。",
    operationHint: "之后可以从稿件回收站恢复。移动文件夹时，里面的文稿也会一起移动。",
    invalidImport: "只能导入 UTF-8 编码的 TXT 或 Markdown 文件，每次最多 50 MB、500 个文稿。",
    operationInvalid: "这里无法执行此操作。",
    operationConflict: "期间稿件发生了变化，因此没有做任何更改。请检查内容后重试。",
    compare: "与当前文稿比较",
    added: "新增",
    removed: "删除",
    copySelection: "复制所选内容",
    copied: "已复制。",
    noChanges: "与当前文稿内容相同。",
    goals: "写作目标",
    enableGoals: "使用目标",
    dailyGoal: "每日目标",
    projectGoal: "作品目标",
    includeSpaces: "空格也计入字数",
    goalHint: "目标按字数计算。今日进度是今天在此设备上增加的字数，删除文字会相应减少。导入、恢复、拆分和合并不计入。换行和图片不计数，资料链接只计算显示的名称。",
  },
};
